// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1OaHqxdfIGq5iK0cam45RxBUiusz1XRQ',
    appId: '1:416827161913:web:eb1bfbee658967a19a7ce8',
    messagingSenderId: '416827161913',
    projectId: 'busprojectnavjot',
    authDomain: 'busprojectnavjot.firebaseapp.com',
    databaseURL: 'https://busprojectnavjot-default-rtdb.firebaseio.com',
    storageBucket: 'busprojectnavjot.appspot.com',
    measurementId: 'G-M61ZHX0DPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJijpmLey0T8r-e3stIwTjlY0Vz0FDhxM',
    appId: '1:416827161913:android:30d8cef82112fd909a7ce8',
    messagingSenderId: '416827161913',
    projectId: 'busprojectnavjot',
    databaseURL: 'https://busprojectnavjot-default-rtdb.firebaseio.com',
    storageBucket: 'busprojectnavjot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPajJZBtm59fd2FFzVQWUPH3_b5nBTyLA',
    appId: '1:416827161913:ios:370a375ba647b3609a7ce8',
    messagingSenderId: '416827161913',
    projectId: 'busprojectnavjot',
    databaseURL: 'https://busprojectnavjot-default-rtdb.firebaseio.com',
    storageBucket: 'busprojectnavjot.appspot.com',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPajJZBtm59fd2FFzVQWUPH3_b5nBTyLA',
    appId: '1:416827161913:ios:cb4e7c6fbfa1a0789a7ce8',
    messagingSenderId: '416827161913',
    projectId: 'busprojectnavjot',
    databaseURL: 'https://busprojectnavjot-default-rtdb.firebaseio.com',
    storageBucket: 'busprojectnavjot.appspot.com',
    iosBundleId: 'com.example.busapp.RunnerTests',
  );
}
